/**
 * @speakerops/db — D1 + Drizzle composition root (section 1.3).
 *
 * Schema: packages/db/schema.ts (E1 path)
 * Migrations: packages/db/migrations/ (linear additive)
 * Repositories: eventId scoping helpers in repository.ts
 */
export {
  organizations,
  events,
  auditEvents,
  outboxEvents,
  idempotencyKeys,
  users,
  authSessions,
  magicLinks,
  eventMemberships,
  rooms,
  tracks,
  designTokenDrafts,
  designTokenPublished,
  fileAssets,
  fileBlobs,
  forms,
  formVersions,
  formFields,
  formRules,
  people,
  submissions,
  submissionAnswers,
  submissionSpeakers,
  evalRounds,
  evalCriteria,
  evalAssignments,
  scores,
  decisions,
  eventParticipations,
  programSessions,
  sessionSpeakers,
  taskTemplates,
  speakerTasks,
  emailTemplates,
  messageJobs,
  messageRecipients,
  deliveryEvents,
  calendarInvites,
  schedulePlacements,
  roomBlockReservations,
  speakerBlockReservations,
  apiKeys,
  projectionRecords,
  savedViews,
  searchDocuments,
  searchIndexState,
  programmePublications,
  portalForms,
  portalFormResponses,
  portalResources,
  fileRequests,
  fileRequestFulfillments,
  baselineTables,
  authTables,
  membershipTables,
  eventSettingsTables,
  designTables,
  formTables,
  submissionTables,
  evalTables,
  decisionTables,
  commsTables,
  scheduleTables,
  apiKeysTables,
  projectionTables,
  gridTables,
  searchTables,
  schema,
  type Organization,
  type NewOrganization,
  type Event,
  type NewEvent,
  type AuditEvent,
  type NewAuditEvent,
  type OutboxEvent,
  type NewOutboxEvent,
  type IdempotencyKey,
  type NewIdempotencyKey,
  type User,
  type NewUser,
  type AuthSession,
  type NewAuthSession,
  type MagicLink,
  type NewMagicLink,
  type EventMembership,
  type NewEventMembership,
  type Room,
  type NewRoom,
  type Track,
  type NewTrack,
  type DesignTokenDraft,
  type NewDesignTokenDraft,
  type DesignTokenPublishedRow,
  type NewDesignTokenPublished,
  type FileAsset,
  type NewFileAsset,
  type Form,
  type NewForm,
  type FormVersion,
  type NewFormVersion,
  type FormField,
  type NewFormField,
  type FormRule,
  type NewFormRule,
  type Person,
  type NewPerson,
  type Submission,
  type NewSubmission,
  type SubmissionAnswer,
  type NewSubmissionAnswer,
  type SubmissionSpeaker,
  type NewSubmissionSpeaker,
  type EvalRound,
  type NewEvalRound,
  type EvalCriterion,
  type NewEvalCriterion,
  type EvalAssignment,
  type NewEvalAssignment,
  type Score,
  type NewScore,
  type Decision,
  type NewDecision,
  type EventParticipation,
  type NewEventParticipation,
  type ProgramSession,
  type NewProgramSession,
  type SessionSpeaker,
  type NewSessionSpeaker,
  type TaskTemplate,
  type NewTaskTemplate,
  type SpeakerTask,
  type NewSpeakerTask,
  type EmailTemplate,
  type NewEmailTemplate,
  type MessageJob,
  type NewMessageJob,
  type MessageRecipient,
  type NewMessageRecipient,
  type DeliveryEvent,
  type NewDeliveryEvent,
  type CalendarInvite,
  type NewCalendarInvite,
  type SchedulePlacement,
  type NewSchedulePlacement,
  type RoomBlockReservation,
  type NewRoomBlockReservation,
  type SpeakerBlockReservation,
  type NewSpeakerBlockReservation,
  type ApiKey,
  type NewApiKey,
  type ProjectionRecord,
  type NewProjectionRecord,
} from "../schema.js";

export {
  createDb,
  SCHEMA_READY,
  type D1DatabaseLike,
  type SpeakerOpsDb,
} from "./client.js";

export {
  requireEventId,
  withEventScope,
  eventScoped,
  buildAuditEventRow,
  MissingEventIdError,
  type EventScopedOptions,
  type AuditWriteInput,
} from "./repository.js";

export {
  migrate,
  inspectSchema,
  defaultDbPath,
  defaultMigrationsDir,
  resolveDbPackageRoot,
  BASELINE_TABLES,
  AUTH_TABLES,
  MEMBERSHIP_TABLES,
  EVENT_SETTINGS_TABLES,
  DESIGN_TABLES,
  FORM_TABLES,
  SUBMISSION_TABLES,
  EVAL_TABLES,
  DECISION_TABLES,
  COMMS_TABLES,
  COMMS_SEND_TABLES,
  SCHEDULE_TABLES,
  API_KEYS_TABLES,
  PROJECTION_TABLES,
  GRID_TABLES,
  SEARCH_TABLES,
  PROGRAMME_TABLES,
  type MigrateOptions,
  type MigrateResult,
} from "./migrate.js";

export const DB_PACKAGE = "@speakerops/db" as const;

export type DbReady = {
  readonly packageName: typeof DB_PACKAGE;
  readonly schemaReady: true;
};

export function createDbMarker(): DbReady {
  return {
    packageName: DB_PACKAGE,
    schemaReady: true,
  };
}

/** @deprecated Use createDbMarker — kept so prior imports fail loudly if still stub-shaped. */
export function createDbPlaceholder(): DbReady {
  return createDbMarker();
}
