/**
 * @speakerops/shared — shared DTOs, Zod schemas, E4 error envelope.
 * Imported by apps/web, apps/api, and packages/cli (no duplicate types).
 */
export {
  ErrorEnvelopeSchema,
  type ErrorEnvelope,
  type ErrorCode,
  errorEnvelope,
  VALIDATION_ERROR,
  UNAUTHORIZED,
  FORBIDDEN,
  NOT_FOUND,
  CONFLICT,
  VERSION,
  INTERNAL_ERROR,
} from "./errors.js";

export { HEALTH_OK, type HealthResponse, HealthResponseSchema } from "./health.js";

export { uuidv7, isUuidv7 } from "./uuid.js";

export {
  EventRoleSchema,
  type EventRole,
  MagicLinkPurposeSchema,
  type MagicLinkPurpose,
  RequestMagicLinkBodySchema,
  type RequestMagicLinkBody,
  RequestMagicLinkResponseSchema,
  type RequestMagicLinkResponse,
  ExchangeMagicLinkBodySchema,
  type ExchangeMagicLinkBody,
  ExchangeMagicLinkResponseSchema,
  type ExchangeMagicLinkResponse,
  SESSION_COOKIE_NAME,
  MAGIC_LINK_TTL_MINUTES,
  SESSION_TTL_DAYS,
  DEFAULT_BOOTSTRAP_EVENT_ID,
  EventListItemSchema,
  type EventListItem,
  EventListResponseSchema,
  type EventListResponse,
} from "./auth.js";

export {
  ScheduleConflictTypeSchema,
  type ScheduleConflictType,
  ScheduleConflictItemSchema,
  type ScheduleConflictItem,
  SchedulePlacementSchema,
  type SchedulePlacementDto,
  SchedulePlaceBodySchema,
  type SchedulePlaceBody,
  SchedulePlaceResponseSchema,
  type SchedulePlaceResponse,
  ScheduleMoveBodySchema,
  type ScheduleMoveBody,
  ScheduleMoveResponseSchema,
  type ScheduleMoveResponse,
  ScheduleUnscheduleBodySchema,
  type ScheduleUnscheduleBody,
  ScheduleUnscheduleResponseSchema,
  type ScheduleUnscheduleResponse,
  ScheduleViewSchema,
  type ScheduleView,
  UnscheduledSessionSchema,
  type UnscheduledSessionDto,
  ScheduleListResponseSchema,
  type ScheduleListResponse,
  ScheduleConflictErrorSchema,
  type ScheduleConflictError,
} from "./schedule.js";

export {
  DEFAULT_ORG_ID,
  TimezoneSchema,
  EventSchema,
  type EventDto,
  EventCreateBodySchema,
  type EventCreateBody,
  EventResponseSchema,
  type EventResponse,
  EventUpdateBodySchema,
  type EventUpdateBody,
  EventListItemFullSchema,
  type EventListItemFull,
  EventListResponseFullSchema,
  type EventListResponseFull,
  RoomSchema,
  type RoomDto,
  RoomUpsertBodySchema,
  type RoomUpsertBody,
  RoomResponseSchema,
  type RoomResponse,
  RoomListResponseSchema,
  type RoomListResponse,
  TrackSchema,
  type TrackDto,
  TrackUpsertBodySchema,
  type TrackUpsertBody,
  TrackResponseSchema,
  type TrackResponse,
  TrackListResponseSchema,
  type TrackListResponse,
} from "./events.js";

export {
  HexColorSchema,
  DesignRadiusSchema,
  type DesignRadius,
  DesignTokensSchema,
  type DesignTokens,
  DesignDraftSchema,
  type DesignDraft,
  DesignPublishedSchema,
  type DesignPublished,
  DesignGetResponseSchema,
  type DesignGetResponse,
  DesignSetDraftBodySchema,
  type DesignSetDraftBody,
  DesignSetDraftResponseSchema,
  type DesignSetDraftResponse,
  DesignPublishBodySchema,
  type DesignPublishBody,
  DesignPublishResponseSchema,
  type DesignPublishResponse,
  PublicDesignResponseSchema,
  type PublicDesignResponse,
  FilePurposeSchema,
  type FilePurpose,
  LOGO_MIME_ALLOWLIST,
  FILE_UPLOAD_MAX_BYTES,
  FILE_PRESIGN_TTL_MS,
  FilePresignBodySchema,
  type FilePresignBody,
  FilePresignResponseSchema,
  type FilePresignResponse,
  FileUploadResponseSchema,
  type FileUploadResponse,
  DEFAULT_DESIGN_TOKENS,
  radiusToCss,
  designTokensToCssVariables,
  softTintFromBrand,
  parseHexRgb,
  rgbToHex,
  relativeLuminance,
  contrastRatio,
  deriveBrandFg,
  validateContrastGate,
  CONTRAST_AA_TEXT,
  CONTRAST_AA_UI,
  type ContrastGateResult,
} from "./design.js";

export {
  VirusScanStatusSchema,
  type VirusScanStatus,
  VIRUS_SCAN_UNSCANNED,
  HEADSHOT_MIME_ALLOWLIST,
  type HeadshotMime,
  SLIDES_MIME_ALLOWLIST,
  type SlidesMime,
  BLOCKED_UPLOAD_MIMES,
  mimeAllowlistForPurpose,
  isBlockedUploadMime,
  FileCompleteBodySchema,
  type FileCompleteBody,
  FileAssetDtoSchema,
  type FileAssetDto,
  FileCompleteResponseSchema,
  type FileCompleteResponse,
} from "./files.js";

export {
  FieldKeySchema,
  type FieldKey,
  FormFieldTypeSchema,
  type FormFieldType,
  FormStatusSchema,
  type FormStatus,
  FormConditionOpSchema,
  type FormConditionOp,
  FormConditionSchema,
  type FormCondition,
  FormFieldConditionsSchema,
  type FormFieldConditions,
  FormFieldOptionSchema,
  type FormFieldOption,
  FormFieldInputSchema,
  type FormFieldInput,
  FormRuleInputSchema,
  type FormRuleInput,
  FormSchema,
  type FormDto,
  FormFieldSchema,
  type FormFieldDto,
  FormRuleSchema,
  type FormRuleDto,
  FormSnapshotSchema,
  type FormSnapshot,
  FormVersionSchema,
  type FormVersionDto,
  FormCreateBodySchema,
  type FormCreateBody,
  FormCreateResponseSchema,
  type FormCreateResponse,
  FormUpdateDraftBodySchema,
  type FormUpdateDraftBody,
  FormUpdateDraftResponseSchema,
  type FormUpdateDraftResponse,
  FormPublishBodySchema,
  type FormPublishBody,
  FormPublishResponseSchema,
  type FormPublishResponse,
  PublicCfpResponseSchema,
  type PublicCfpResponse,
  FORM_DRAFT_VERSION_NUM,
} from "./forms.js";

export {
  SubmissionStatusSchema,
  type SubmissionStatus,
  CFP_MIN_SPEAKERS,
  CFP_MAX_SPEAKERS,
  TURNSTILE_TEST_SITE_KEY,
  TURNSTILE_TEST_SECRET_PASS,
  TURNSTILE_TEST_SECRET_FAIL,
  TURNSTILE_DEV_PASS_TOKEN,
  TURNSTILE_DEV_FAIL_TOKEN,
  CFP_RATE_LIMIT_MAX,
  CFP_RATE_LIMIT_WINDOW_MS,
  CFP_FILE_MIME_ALLOWLIST,
  type CfpFileMime,
  CFP_FILE_MAX_BYTES,
  CfpWindowStateSchema,
  type CfpWindowState,
  SubmissionSpeakerInputSchema,
  type SubmissionSpeakerInput,
  SubmissionAnswerInputSchema,
  type SubmissionAnswerInput,
  SubmissionCreateBodySchema,
  type SubmissionCreateBody,
  SubmissionSpeakerDtoSchema,
  type SubmissionSpeakerDto,
  SubmissionAnswerDtoSchema,
  type SubmissionAnswerDto,
  SubmissionSchema,
  type SubmissionDto,
  SubmissionCreateResponseSchema,
  type SubmissionCreateResponse,
  CfpFileUploadBodySchema,
  type CfpFileUploadBody,
  CfpFileUploadResponseSchema,
  type CfpFileUploadResponse,
  PublicCfpMetaSchema,
  type PublicCfpMeta,
  evaluateFormCondition,
  deriveCategoryFromRules,
  isFieldVisible,
  computeCfpWindowState,
} from "./submissions.js";

export {
  EvalRoundStatusSchema,
  type EvalRoundStatus,
  EvalAssignmentStatusSchema,
  type EvalAssignmentStatus,
  EvalCriterionInputSchema,
  type EvalCriterionInput,
  EvalUpsertRubricBodySchema,
  type EvalUpsertRubricBody,
  EvalCriterionSchema,
  type EvalCriterionDto,
  EvalRoundSchema,
  type EvalRoundDto,
  EvalRubricResponseSchema,
  type EvalRubricResponse,
  EvalScoreItemSchema,
  type EvalScoreItem,
  EvalScoreBodySchema,
  type EvalScoreBody,
  ScoreDtoSchema,
  type ScoreDto,
  EvalAssignmentSchema,
  type EvalAssignmentDto,
  EvalScoreResponseSchema,
  type EvalScoreResponse,
  EvalQueueItemSchema,
  type EvalQueueItem,
  EvalQueueResponseSchema,
  type EvalQueueResponse,
  SubmissionAssignBodySchema,
  type SubmissionAssignBody,
  SubmissionAssignResponseSchema,
  type SubmissionAssignResponse,
  EvalAdminSubmissionRollupSchema,
  type EvalAdminSubmissionRollup,
  EvalAdminRollupResponseSchema,
  type EvalAdminRollupResponse,
  computeWeightedAggregate,
} from "./eval.js";

export {
  DecisionValueSchema,
  type DecisionValue,
  DecisionRecordBodySchema,
  type DecisionRecordBody,
  DecisionSchema,
  type DecisionDto,
  ProgramSessionSchema,
  type ProgramSessionDto,
  EventParticipationSchema,
  type EventParticipationDto,
  SpeakerTaskSchema,
  type SpeakerTaskDto,
  TaskTemplateSchema,
  type TaskTemplateDto,
  DecisionRecordResponseSchema,
  type DecisionRecordResponse,
  DirectSessionSpeakerSchema,
  type DirectSessionSpeaker,
  DirectSessionBodySchema,
  type DirectSessionBody,
  DirectSessionResponseSchema,
  type DirectSessionResponse,
  SubmissionListQuerySchema,
  type SubmissionListQuery,
  SubmissionListItemSchema,
  type SubmissionListItem,
  SubmissionListResponseSchema,
  type SubmissionListResponse,
  SubmissionDetailResponseSchema,
  type SubmissionDetailResponse,
  BulkDecisionPreviewBodySchema,
  type BulkDecisionPreviewBody,
  BulkDecisionPreviewItemSchema,
  type BulkDecisionPreviewItem,
  BulkDecisionPreviewResponseSchema,
  type BulkDecisionPreviewResponse,
} from "./decisions.js";

export {
  ParticipationProfileSchema,
  type ParticipationProfileDto,
  PortalTaskSchema,
  type PortalTaskDto,
  PortalHomeQuerySchema,
  type PortalHomeQuery,
  PortalHomeResponseSchema,
  type PortalHomeResponse,
  ParticipationUpdateProfileBodySchema,
  type ParticipationUpdateProfileBody,
  ParticipationUpdateProfileResponseSchema,
  type ParticipationUpdateProfileResponse,
  TaskCompleteBodySchema,
  type TaskCompleteBody,
  TaskCompleteResponseSchema,
  type TaskCompleteResponse,
  AdminSpeakerListItemSchema,
  type AdminSpeakerListItem,
  AdminSpeakersListQuerySchema,
  type AdminSpeakersListQuery,
  AdminSpeakersListResponseSchema,
  type AdminSpeakersListResponse,
  SpeakerFileMetaSchema,
  type SpeakerFileMetaDto,
  AdminSpeakerDetailResponseSchema,
  type AdminSpeakerDetailResponse,
  TaskTemplateCreateBodySchema,
  type TaskTemplateCreateBody,
  TaskTemplateUpdateBodySchema,
  type TaskTemplateUpdateBody,
  TaskTemplateListResponseSchema,
  type TaskTemplateListResponse,
  TaskTemplateResponseSchema,
  type TaskTemplateResponse,
  TaskTemplateDeleteBodySchema,
  type TaskTemplateDeleteBody,
  TaskTemplateDeleteResponseSchema,
  type TaskTemplateDeleteResponse,
} from "./portal.js";

export {
  TemplateKeySchema,
  type TemplateKey,
  EmailTemplateSchema,
  type EmailTemplateDto,
  CommsUpsertTemplateBodySchema,
  type CommsUpsertTemplateBody,
  CommsUpsertTemplateResponseSchema,
  type CommsUpsertTemplateResponse,
  CommsSegmentSchema,
  type CommsSegment,
  CommsPreviewBodySchema,
  type CommsPreviewBody,
  CommsPreviewRecipientSchema,
  type CommsPreviewRecipient,
  CommsPreviewBodyItemSchema,
  type CommsPreviewBodyItem,
  CommsPreviewResponseSchema,
  type CommsPreviewResponse,
  CommsSendBodySchema,
  type CommsSendBody,
  MessageJobStatusSchema,
  type MessageJobStatus,
  MessageJobSchema,
  type MessageJobDto,
  CommsSendResponseSchema,
  type CommsSendResponse,
  COMMS_OUTBOX_TOPIC,
  CommsListTemplatesResponseSchema,
  type CommsListTemplatesResponse,
  CommsJobSummarySchema,
  type CommsJobSummary,
  CommsListJobsResponseSchema,
  type CommsListJobsResponse,
  MessageRecipientSchema,
  type MessageRecipientDto,
  DeliveryEventSchema,
  type DeliveryEventDto,
  CommsGetJobResponseSchema,
  type CommsGetJobResponse,
  CalendarInviteSchema,
  type CalendarInviteDto,
  CommsListIcsResponseSchema,
  type CommsListIcsResponse,
  IsoDateTimeStringSchema,
  CommsIcsForPlacementBodySchema,
  type CommsIcsForPlacementBody,
  CommsIcsForPlacementResponseSchema,
  type CommsIcsForPlacementResponse,
  extractMergeFields,
  renderMergeFields,
} from "./comms.js";

export {
  ReportsReadinessQuerySchema,
  type ReportsReadinessQuery,
  ReadinessTaskStatusSchema,
  type ReadinessTaskStatus,
  ReadinessOutstandingItemSchema,
  type ReadinessOutstandingItem,
  ReadinessStatsSchema,
  type ReadinessStats,
  ReportsReadinessResponseSchema,
  type ReportsReadinessResponse,
  isTaskOverdue,
} from "./readiness.js";
