/**
 * @speakerops/shared — shared DTOs, Zod schemas, E4 error envelope.
 * Imported by apps/web, apps/api, and packages/cli (no duplicate types).
 */
export {
  ErrorEnvelopeSchema,
  type ErrorEnvelope,
  type ErrorCode,
  errorEnvelope,
  VALIDATION_ERROR,
  UNAUTHORIZED,
  FORBIDDEN,
  NOT_FOUND,
  CONFLICT,
  VERSION,
  INTERNAL_ERROR,
} from "./errors.js";

export {
  CONTENT_SECURITY_POLICY,
  CONTENT_SECURITY_POLICY_DEV,
  SECURITY_HEADERS,
  SECURITY_HEADERS_DEV,
  RATE_LIMITED,
  type SecurityHeaderName,
} from "./security.js";

export { HEALTH_OK, type HealthResponse, HealthResponseSchema } from "./health.js";

export { uuidv7, isUuidv7 } from "./uuid.js";

export {
  EventRoleSchema,
  type EventRole,
  MagicLinkPurposeSchema,
  type MagicLinkPurpose,
  RequestMagicLinkBodySchema,
  type RequestMagicLinkBody,
  RequestMagicLinkResponseSchema,
  type RequestMagicLinkResponse,
  AUTH_MAGIC_LINK_OUTBOX_TOPIC,
  ExchangeMagicLinkBodySchema,
  type ExchangeMagicLinkBody,
  ExchangeMagicLinkResponseSchema,
  type ExchangeMagicLinkResponse,
  AuthMembershipOptionSchema,
  type AuthMembershipOption,
  MeMembershipsResponseSchema,
  type MeMembershipsResponse,
  DevRoleSwitchBodySchema,
  type DevRoleSwitchBody,
  DevRoleSwitchResponseSchema,
  type DevRoleSwitchResponse,
  JudgeAccessBodySchema,
  type JudgeAccessBody,
  JudgeAccessResponseSchema,
  type JudgeAccessResponse,
  DEMO_ROLE_EMAILS,
  SESSION_COOKIE_NAME,
  JUDGE_SESSION_COOKIE_NAME,
  MAGIC_LINK_TTL_MINUTES,
  SESSION_TTL_DAYS,
  DEFAULT_BOOTSTRAP_EVENT_ID,
  EventListItemSchema,
  type EventListItem,
  EventListResponseSchema,
  type EventListResponse,
} from "./auth.js";

export {
  ScheduleConflictTypeSchema,
  type ScheduleConflictType,
  ScheduleConflictItemSchema,
  type ScheduleConflictItem,
  SchedulePlacementSchema,
  type SchedulePlacementDto,
  SchedulePlaceBodySchema,
  type SchedulePlaceBody,
  SchedulePlaceResponseSchema,
  type SchedulePlaceResponse,
  ScheduleMoveBodySchema,
  type ScheduleMoveBody,
  ScheduleMoveResponseSchema,
  type ScheduleMoveResponse,
  ScheduleUnscheduleBodySchema,
  type ScheduleUnscheduleBody,
  ScheduleUnscheduleResponseSchema,
  type ScheduleUnscheduleResponse,
  ScheduleViewSchema,
  type ScheduleView,
  UnscheduledSessionSchema,
  type UnscheduledSessionDto,
  ScheduleListResponseSchema,
  type ScheduleListResponse,
  ScheduleConflictErrorSchema,
  type ScheduleConflictError,
} from "./schedule.js";

export {
  DEFAULT_ORG_ID,
  TimezoneSchema,
  EventSchema,
  type EventDto,
  EventCreateBodySchema,
  type EventCreateBody,
  EventResponseSchema,
  type EventResponse,
  EventUpdateBodySchema,
  type EventUpdateBody,
  EventListItemFullSchema,
  type EventListItemFull,
  EventListResponseFullSchema,
  type EventListResponseFull,
  RoomSchema,
  type RoomDto,
  RoomUpsertBodySchema,
  type RoomUpsertBody,
  RoomResponseSchema,
  type RoomResponse,
  RoomListResponseSchema,
  type RoomListResponse,
  TrackSchema,
  type TrackDto,
  TrackUpsertBodySchema,
  type TrackUpsertBody,
  TrackResponseSchema,
  type TrackResponse,
  TrackListResponseSchema,
  type TrackListResponse,
  EventMemberSchema,
  type EventMember,
  EventMembersResponseSchema,
  type EventMembersResponse,
} from "./events.js";

export {
  HexColorSchema,
  DesignRadiusSchema,
  type DesignRadius,
  DesignTokensSchema,
  type DesignTokens,
  DesignDraftSchema,
  type DesignDraft,
  DesignPublishedSchema,
  type DesignPublished,
  DesignGetResponseSchema,
  type DesignGetResponse,
  DesignSetDraftBodySchema,
  type DesignSetDraftBody,
  DesignSetDraftResponseSchema,
  type DesignSetDraftResponse,
  DesignPublishBodySchema,
  type DesignPublishBody,
  DesignPublishResponseSchema,
  type DesignPublishResponse,
  PublicDesignResponseSchema,
  type PublicDesignResponse,
  FilePurposeSchema,
  type FilePurpose,
  LOGO_MIME_ALLOWLIST,
  FILE_UPLOAD_MAX_BYTES,
  FILE_PRESIGN_TTL_MS,
  FilePresignBodySchema,
  type FilePresignBody,
  FilePresignResponseSchema,
  type FilePresignResponse,
  FileUploadResponseSchema,
  type FileUploadResponse,
  DEFAULT_DESIGN_TOKENS,
  radiusToCss,
  designTokensToCssVariables,
  softTintFromBrand,
  parseHexRgb,
  rgbToHex,
  relativeLuminance,
  contrastRatio,
  deriveBrandFg,
  validateContrastGate,
  CONTRAST_AA_TEXT,
  CONTRAST_AA_UI,
  type ContrastGateResult,
} from "./design.js";

export {
  VirusScanStatusSchema,
  type VirusScanStatus,
  VIRUS_SCAN_UNSCANNED,
  HEADSHOT_MIME_ALLOWLIST,
  type HeadshotMime,
  SLIDES_MIME_ALLOWLIST,
  type SlidesMime,
  BLOCKED_UPLOAD_MIMES,
  mimeAllowlistForPurpose,
  isBlockedUploadMime,
  FileCompleteBodySchema,
  type FileCompleteBody,
  FileAssetDtoSchema,
  type FileAssetDto,
  FileCompleteResponseSchema,
  type FileCompleteResponse,
} from "./files.js";

export {
  FieldKeySchema,
  type FieldKey,
  FormFieldTypeSchema,
  type FormFieldType,
  FORM_FIELD_MAX_CHARS_TYPES,
  FORM_FIELD_MAX_CHARS_MIN,
  FORM_FIELD_MAX_CHARS_MAX,
  fieldTypeSupportsMaxChars,
  CFP_SPEAKERS_BOUND_MIN,
  CFP_SPEAKERS_BOUND_MAX,
  FormStatusSchema,
  type FormStatus,
  FormNodeKindSchema,
  type FormNodeKind,
  FormLayoutTypeSchema,
  type FormLayoutType,
  FORM_SECTION_LABEL_MAX,
  isLayoutNode,
  isInputNode,
  FormConditionOpSchema,
  type FormConditionOp,
  FormConditionSchema,
  type FormCondition,
  FormFieldConditionsSchema,
  type FormFieldConditions,
  FormFieldOptionSchema,
  type FormFieldOption,
  FormFieldInputSchema,
  type FormFieldInput,
  FormRuleInputSchema,
  type FormRuleInput,
  FormSchema,
  type FormDto,
  FormFieldSchema,
  type FormFieldDto,
  FormRuleSchema,
  type FormRuleDto,
  FormSnapshotSchema,
  type FormSnapshot,
  FormVersionSchema,
  type FormVersionDto,
  FormCreateBodySchema,
  type FormCreateBody,
  FormCreateResponseSchema,
  type FormCreateResponse,
  FormUpdateDraftBodySchema,
  type FormUpdateDraftBody,
  FormUpdateDraftResponseSchema,
  type FormUpdateDraftResponse,
  FormPublishBodySchema,
  type FormPublishBody,
  FormPublishResponseSchema,
  type FormPublishResponse,
  PublicCfpResponseSchema,
  type PublicCfpResponse,
  FormListResponseSchema,
  type FormListResponse,
  FormAdminGetResponseSchema,
  type FormAdminGetResponse,
  FORM_DRAFT_VERSION_NUM,
} from "./forms.js";

export {
  SUBMISSION_CONFIRMATION_TEMPLATE_KEY,
  submissionConfirmationIdempotencyKey,
  SUBMISSION_CONFIRMATION_DEFAULT_SUBJECT,
  SUBMISSION_CONFIRMATION_DEFAULT_BODY,
  EventNotificationSettingsSchema,
  type EventNotificationSettings,
  type ResolvedEventNotificationSettings,
  parseEventNotificationSettings,
  mergeEventNotificationSettings,
  parseNotifyEmailsInput,
} from "./lifecycle.js";

export {
  SubmissionStatusSchema,
  type SubmissionStatus,
  SUBMISSION_EVAL_ELIGIBLE_STATUSES,
  SUBMISSION_DECISION_SOURCE_STATUSES,
  isSubmissionEvalEligible,
  isSubmissionDecisionSource,
  CFP_MIN_SPEAKERS,
  CFP_MAX_SPEAKERS,
  CFP_SPEAKERS_HARD_MIN,
  CFP_SPEAKERS_HARD_MAX,
  TURNSTILE_TEST_SITE_KEY,
  TURNSTILE_TEST_SECRET_PASS,
  TURNSTILE_TEST_SECRET_FAIL,
  TURNSTILE_DEV_PASS_TOKEN,
  TURNSTILE_DEV_FAIL_TOKEN,
  CFP_RATE_LIMIT_MAX,
  CFP_RATE_LIMIT_WINDOW_MS,
  CFP_FILE_MIME_ALLOWLIST,
  type CfpFileMime,
  CFP_FILE_MAX_BYTES,
  CfpWindowStateSchema,
  type CfpWindowState,
  SubmissionSpeakerInputSchema,
  type SubmissionSpeakerInput,
  SubmissionAnswerInputSchema,
  type SubmissionAnswerInput,
  SubmissionCreateBodySchema,
  type SubmissionCreateBody,
  SubmissionSaveDraftBodySchema,
  type SubmissionSaveDraftBody,
  SubmissionDraftSnapshotSchema,
  type SubmissionDraftSnapshot,
  SubmissionSaveDraftResponseSchema,
  type SubmissionSaveDraftResponse,
  SubmissionGetDraftResponseSchema,
  type SubmissionGetDraftResponse,
  SubmissionSpeakerDtoSchema,
  type SubmissionSpeakerDto,
  SubmissionAnswerDtoSchema,
  type SubmissionAnswerDto,
  SubmissionSchema,
  type SubmissionDto,
  SubmissionCreateResponseSchema,
  type SubmissionCreateResponse,
  CfpFileUploadBodySchema,
  type CfpFileUploadBody,
  CfpFileUploadResponseSchema,
  type CfpFileUploadResponse,
  PublicCfpMetaSchema,
  type PublicCfpMeta,
  evaluateFormCondition,
  deriveCategoryFromRules,
  isFieldVisible,
  computeCfpWindowState,
} from "./submissions.js";

export {
  EvalRoundStatusSchema,
  type EvalRoundStatus,
  EvalAssignmentStatusSchema,
  type EvalAssignmentStatus,
  EvalCriterionInputSchema,
  type EvalCriterionInput,
  EvalUpsertRubricBodySchema,
  type EvalUpsertRubricBody,
  EvalCriterionSchema,
  type EvalCriterionDto,
  EvalRoundSchema,
  type EvalRoundDto,
  EvalRubricResponseSchema,
  type EvalRubricResponse,
  EvalScoreItemSchema,
  type EvalScoreItem,
  EvalScoreBodySchema,
  type EvalScoreBody,
  EvalAbstainBodySchema,
  type EvalAbstainBody,
  EvalAbstainResponseSchema,
  type EvalAbstainResponse,
  ScoreDtoSchema,
  type ScoreDto,
  EvalAssignmentSchema,
  type EvalAssignmentDto,
  EvalScoreResponseSchema,
  type EvalScoreResponse,
  EvalQueueItemSchema,
  type EvalQueueItem,
  EvalQueueResponseSchema,
  type EvalQueueResponse,
  EvalProposalAnswerSchema,
  type EvalProposalAnswer,
  EvalProposalSpeakerSchema,
  type EvalProposalSpeaker,
  EvalProposalResponseSchema,
  type EvalProposalResponse,
  SubmissionAssignBodySchema,
  type SubmissionAssignBody,
  SubmissionAssignResponseSchema,
  type SubmissionAssignResponse,
  EvalAdminSubmissionRollupSchema,
  type EvalAdminSubmissionRollup,
  EvalAdminRollupResponseSchema,
  type EvalAdminRollupResponse,
  EvalReviewScoreSchema,
  type EvalReviewScore,
  EvalReviewItemSchema,
  type EvalReviewItem,
  EvalReviewsResponseSchema,
  type EvalReviewsResponse,
  computeWeightedAggregate,
  computeScoreSpread,
  coerceFiniteNumber,
  isEvalRoundClosed,
  EvalScoreSortSchema,
  type EvalScoreSort,
  type EvalSortableSubmission,
  sortEvalSubmissionsByScore,
  csvEscapeField,
  neutralizeCsvFormula,
  type EvalCsvRow,
  evalRollupToCsv,
} from "./eval.js";

export {
  DecisionValueSchema,
  type DecisionValue,
  DecisionRecordBodySchema,
  type DecisionRecordBody,
  DecisionSchema,
  type DecisionDto,
  ProgramSessionSchema,
  type ProgramSessionDto,
  EventParticipationSchema,
  type EventParticipationDto,
  SpeakerTaskSchema,
  type SpeakerTaskDto,
  TaskTemplateSchema,
  type TaskTemplateDto,
  DecisionRecordResponseSchema,
  type DecisionRecordResponse,
  DirectSessionSpeakerSchema,
  type DirectSessionSpeaker,
  DirectSessionBodySchema,
  type DirectSessionBody,
  DirectSessionResponseSchema,
  type DirectSessionResponse,
  SUBMISSION_LIST_DEFAULT_LIMIT,
  SUBMISSION_LIST_MAX_LIMIT,
  SubmissionListQuerySchema,
  type SubmissionListQuery,
  SubmissionListItemSchema,
  type SubmissionListItem,
  SubmissionListResponseSchema,
  type SubmissionListResponse,
  SubmissionDetailResponseSchema,
  type SubmissionDetailResponse,
  BulkDecisionPreviewBodySchema,
  type BulkDecisionPreviewBody,
  BulkDecisionPreviewItemSchema,
  type BulkDecisionPreviewItem,
  BulkDecisionPreviewResponseSchema,
  type BulkDecisionPreviewResponse,
  BulkDecisionCommitBodySchema,
  type BulkDecisionCommitBody,
  BulkDecisionCommitItemSchema,
  type BulkDecisionCommitItem,
  BulkDecisionCommitResponseSchema,
  type BulkDecisionCommitResponse,
} from "./decisions.js";

export {
  ParticipationProfileSchema,
  type ParticipationProfileDto,
  PortalTaskSchema,
  type PortalTaskDto,
  PortalHomeQuerySchema,
  type PortalHomeQuery,
  PortalHomeResponseSchema,
  type PortalHomeResponse,
  PortalFileItemSchema,
  type PortalFileItem,
  PortalSessionPlacementSchema,
  type PortalSessionPlacement,
  PortalSessionSchema,
  type PortalSessionDto,
  PortalReadinessStateSchema,
  type PortalReadinessState,
  PortalReadinessSchema,
  type PortalReadiness,
  ParticipationUpdateProfileBodySchema,
  type ParticipationUpdateProfileBody,
  ParticipationUpdateProfileResponseSchema,
  type ParticipationUpdateProfileResponse,
  TaskCompleteBodySchema,
  type TaskCompleteBody,
  TaskCompleteResponseSchema,
  type TaskCompleteResponse,
  AdminSpeakerListItemSchema,
  type AdminSpeakerListItem,
  AdminSpeakersListQuerySchema,
  type AdminSpeakersListQuery,
  AdminSpeakersListResponseSchema,
  type AdminSpeakersListResponse,
  SpeakerFileMetaSchema,
  type SpeakerFileMetaDto,
  AdminSpeakerDetailResponseSchema,
  type AdminSpeakerDetailResponse,
  SpeakersUpdateProfileBodySchema,
  type SpeakersUpdateProfileBody,
  SpeakersUpdateProfileResponseSchema,
  type SpeakersUpdateProfileResponse,
  TaskTemplateCreateBodySchema,
  type TaskTemplateCreateBody,
  TaskTemplateUpdateBodySchema,
  type TaskTemplateUpdateBody,
  TaskTemplateListResponseSchema,
  type TaskTemplateListResponse,
  TaskTemplateResponseSchema,
  type TaskTemplateResponse,
  TaskTemplateDeleteBodySchema,
  type TaskTemplateDeleteBody,
  TaskTemplateDeleteResponseSchema,
  type TaskTemplateDeleteResponse,
} from "./portal.js";

export {
  TemplateKeySchema,
  type TemplateKey,
  EmailTemplateSchema,
  type EmailTemplateDto,
  CommsUpsertTemplateBodySchema,
  type CommsUpsertTemplateBody,
  CommsUpsertTemplateResponseSchema,
  type CommsUpsertTemplateResponse,
  CommsSegmentSchema,
  type CommsSegment,
  CommsPreviewBodySchema,
  type CommsPreviewBody,
  CommsPreviewRecipientSchema,
  type CommsPreviewRecipient,
  CommsPreviewBodyItemSchema,
  type CommsPreviewBodyItem,
  CommsPreviewResponseSchema,
  type CommsPreviewResponse,
  CommsSendBodySchema,
  type CommsSendBody,
  MessageJobStatusSchema,
  type MessageJobStatus,
  MessageJobSchema,
  type MessageJobDto,
  CommsSendResponseSchema,
  type CommsSendResponse,
  COMMS_OUTBOX_TOPIC,
  CommsListTemplatesResponseSchema,
  type CommsListTemplatesResponse,
  CommsJobSummarySchema,
  type CommsJobSummary,
  CommsListJobsResponseSchema,
  type CommsListJobsResponse,
  MessageRecipientSchema,
  type MessageRecipientDto,
  DeliveryEventSchema,
  type DeliveryEventDto,
  CommsGetJobResponseSchema,
  type CommsGetJobResponse,
  CalendarInviteSchema,
  type CalendarInviteDto,
  CommsListIcsResponseSchema,
  type CommsListIcsResponse,
  IsoDateTimeStringSchema,
  CommsIcsForPlacementBodySchema,
  type CommsIcsForPlacementBody,
  CommsIcsForPlacementResponseSchema,
  type CommsIcsForPlacementResponse,
  extractMergeFields,
  renderMergeFields,
} from "./comms.js";

export {
  ReportsReadinessQuerySchema,
  type ReportsReadinessQuery,
  ReadinessTaskStatusSchema,
  type ReadinessTaskStatus,
  ReadinessOutstandingItemSchema,
  type ReadinessOutstandingItem,
  ReadinessStatsSchema,
  type ReadinessStats,
  ReportsReadinessResponseSchema,
  type ReportsReadinessResponse,
  READINESS_OUTSTANDING_LIST_CAP,
  isTaskOverdue,
} from "./readiness.js";

export {
  API_SCOPES,
  type ApiScope,
  ApiScopeSchema,
  DEFAULT_DENY_SCOPES,
  type DefaultDenyScope,
  DEFAULT_DENY_SCOPE_SET,
  SAFE_DEFAULT_SCOPES,
  API_KEY_CREATED_AT_FALLBACK,
  ApiKeySchema,
  type ApiKeyDto,
  KeysListResponseSchema,
  type KeysListResponse,
  KeysCreateBodySchema,
  type KeysCreateBody,
  KeysCreateResponseSchema,
  type KeysCreateResponse,
  KeysRevokeResponseSchema,
  type KeysRevokeResponse,
  scopesAreValid,
  keyHasScopes,
} from "./keys.js";

export {
  AIRTABLE_OUTBOX_TOPIC,
  AIRTABLE_PROJECTION_SYSTEM,
  AirtableEntityTypeSchema,
  type AirtableEntityType,
  DEFAULT_AIRTABLE_TABLES,
  AirtableProjectPayloadSchema,
  type AirtableProjectPayload,
  AirtableLagSchema,
  type AirtableLag,
  AirtableStatusErrorSchema,
  type AirtableStatusError,
  ReportsAirtableStatusResponseSchema,
  type ReportsAirtableStatusResponse,
} from "./airtable.js";
